// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © cpirkk

//@version=5

//SUBSCRIBE TO CHEAT CODE!!!
//
//

//
//SUBSCRIBE TO CHEAT CODE!!!
strategy("Cheat Codes Example", overlay = true)

//RSI

rsi = ta.rsi(close, 14)


//ENTRY

LC1 = ta.crossover(ta.sma(close,21), ta.sma(close,100))
LC2 = ta.sma(close, 200) > close
if (LC1) and (LC2) 
    strategy.entry("BULL CALL", strategy.long)
    

SC1 = ta.sma(close, 200) < close
SC2 = ta.crossunder(rsi, 55)
if (SC1) and (SC2)
    strategy.entry("BEAR CALL", strategy.short)
    
    // BEST PAIRINGS:
    // BTC: 10M
    // MATIC: 10M
    // ETH: 10M
    // FIL: 10M
    // :) 